### ISSUE TITLE
Link to documentation is dead

### ISSUE THREAD

**Issue by fotisj** [googleworkspace/PyDrive#125]
The link to the documentation on the home page of the project (README.rst) is dead:

https://googledrive.github.io/PyDrive/docs/build/html/index.html

**Comment by ludwigschubert** [comment]
I believe it just needs to be updated to reflect the new username:
[https://~googledrive~gsuitedevs.github.io/PyDrive/docs/build/html/index.html](https://gsuitedevs.github.io/PyDrive/docs/build/html/index.html)

**Comment by MarkSDS** [comment]
In fact, most of all external links on 
https://github.com/gsuitedevs/PyDrive/blob/master/docs/oauth.rst
are dead.
